language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

script:
  - composer install -n
  - phpunit --coverage-clover=coverage.xml --configuration=phpunit.xml

after_script:
 - bash <(curl -s https://codecov.io/bash)
